#!/usr/bin/with-contenv bash
# vim: set ft=bash

if [ -e "/detach_sess/.rtorrent" ]; then
rm -f /detach_sess/.rtorrent || true
sleep 1s
fi

TERM=xterm-256color dtach -n /detach_sess/.rtorrent \
s6-setuidgid abc /usr/local/bin/rtorrent \
-n -o import=/config/rtorrent/rtorrent.rc

until [ -e "/config/rtorrent/rtorrent_sess/rtorrent.lock" ];
do
sleep 1s
done

until
   rtorrent_pid=$(cut -d '+' -f 2 /config/rtorrent/rtorrent_sess/rtorrent.lock) && \
   [ -n "$rtorrent_pid" ]
do
   sleep 1
done
print "rTorrent pid: $rtorrent_pid"
tail -n 1 -f /config/log/rtorrent/rtorrent.log
